theme: jekyll-theme-midnight
title: Dodge Battle
site_url: https://chriswestwood.github.io/DodgeBattle/
repo_name: 'chriswestwood/DodgeBattle'
repo_url: 'https://github.com/chriswestwood/DodgeBattle'
